DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "CRVENI"
DEF PLAYERNAME2 EQUS "EŠ"
DEF PLAYERNAME3 EQUS "MARKO"

DEF RIVALNAME1 EQUS "PLAVI"
DEF RIVALNAME2 EQUS "GARI"
DEF RIVALNAME3 EQUS "IVAN"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "PLAVI"
DEF PLAYERNAME2 EQUS "EŠ"
DEF PLAYERNAME3 EQUS "IVAN"

DEF RIVALNAME1 EQUS "CRVENI"
DEF RIVALNAME2 EQUS "GARI"
DEF RIVALNAME3 EQUS "MARKO"
ENDC
